### ISSUE TITLE
Darkmode targetSDK 33 Android (might need to adjust)

### ISSUE THREAD

**Issue by spoxies** [timbru31/cordova-plugin-android-dark-mode-support#57]
Since the targetSDK 33 on Android WebView the behaviour of darkmode has changed. 
It now could 'work' without the plugin however out of the box it does not function at all.
That includes whilst using this plugin. 

My finding are based on using using ionic-webview

The change that one should make in order for it to work (again) is change the style of the app theme in
`cordova/platforms/android/app/src/main/res/values/styles.xml`

`@style/Theme.AppCompat.Light.NoActionBar` to `@style/Theme.AppCompat.DayNight.NoActionBar`

Note that with this change it does not propagate when the phone theme is changed (ligt, dark) while the app is still open.

Old:
```xml
<?xml version="1.0" encoding="utf-8"?>
<resources xmlns:tools="http://schemas.android.com/tools">
    <style name="AppTheme" parent="@style/Theme.AppCompat.Light.NoActionBar">
        <item name="android:windowBackground">@android:color/white</item>
        <item name="android:statusBarColor">@android:color/white</item>
        <item name="android:windowLightStatusBar" tools:targetApi="m">true</item>
    </style>
</resources>
```

new 
```xml
<?xml version="1.0" encoding="utf-8"?>
<resources xmlns:tools="http://schemas.android.com/tools">
    <style name="AppTheme" parent="@style/Theme.AppCompat.DayNight.NoActionBar">
        <item name="android:windowBackground">@android:color/white</item>
        <item name="android:statusBarColor">@android:color/white</item>
        <item name="android:windowLightStatusBar" tools:targetApi="m">true</item>
    </style>
```
</resources>

**Comment by timbru31** [comment]
Thanks, I'll take a look!

**Comment by timbru31** [comment]
You can achieve the same change with the following preference in your config.xml

```xml
        <preference name="AndroidPostSplashScreenTheme" value="@style/Theme.AppCompat.DayNight.NoActionBar" />
```

I'll publish a new version, too and also update the usage guide.
